# Generated by Django 5.2.4 on 2025-07-15 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_useranswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='subject',
            field=models.CharField(default='None', max_length=100),
            preserve_default=False,
        ),
    ]
