# Generated by Django 5.2.4 on 2025-07-26 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_exam_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='passage',
            field=models.TextField(blank=True, null=True),
        ),
    ]
