# Generated by Django 5.2.4 on 2025-07-26 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_quiz_passage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='passage',
        ),
        migrations.AddField(
            model_name='question',
            name='passage',
            field=models.TextField(blank=True, null=True),
        ),
    ]
