# Generated by Django 5.2.4 on 2025-07-26 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_quiz_passage_question_passage'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='chart_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
