# Generated by Django 5.2.4 on 2025-08-02 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_question_chart_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='marks_per_correct_answer',
            field=models.FloatField(default=4.0),
        ),
        migrations.AddField(
            model_name='exam',
            name='negative_marks_per_wrong_answer',
            field=models.FloatField(default=1.0),
        ),
    ]
