# Generated by Django 5.2.4 on 2025-08-02 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_exam_marks_per_correct_answer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useranswer',
            name='selected_option',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
